name: ecopraia
description: "Praia+Segura - Mapa interativo de praias com informações de segurança"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  font_awesome_flutter: ^10.6.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  provider: ^6.0.0
  dio: ^5.0.0
  geolocator: ^12.0.0
  url_launcher: ^6.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  # Dependências web
  # google_maps_flutter_web removido
  geolocator_web: ^4.0.0
  url_launcher_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
