// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuncJ3YUL_0Mbvlsdf1EIcXI9XJ_bhp8',
    appId: '1:910835657702:web:532ff06cf8e5b880e60427',
    messagingSenderId: '910835657702',
    projectId: 'ecopraia-b69db',
    authDomain: 'ecopraia-b69db.firebaseapp.com',
    storageBucket: 'ecopraia-b69db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnIgF5kSxFIhBPu5Gg8JjA3cn_zozUOk',
    appId: '1:910835657702:android:218437e653acbe12e60427',
    messagingSenderId: '910835657702',
    projectId: 'ecopraia-b69db',
    storageBucket: 'ecopraia-b69db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4O0fbnPhyhljvQ76NaPljLCyPZQORZbU',
    appId: '1:910835657702:ios:bc44f7309c1f5e89e60427',
    messagingSenderId: '910835657702',
    projectId: 'ecopraia-b69db',
    storageBucket: 'ecopraia-b69db.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
